---
# tasks file for myvhost
#############################
# * (faild_when) 플랫폼 점검 & 버전 점검 - CentOS 9
# * (dnf)웹 패키지 설치
# * (template)웹 서버 설정 - /etc/httpd/conf.d/vhost.conf
# * (systemd)웹 서비스 기동
# * (firewalld)방화벽에 포트 등록
#############################
- name: 배포판 및 버전 확인
  ansible.builtin.debug:
    msg: "[정보] CentOS Stream 9 버전에서만 동작합니다"
  failed_when: >
    ansible_distribution != "CentOS" or
    ansible_distribution_version != "9"

- name: 웹 패키지 설치
  ansible.builtin.yum:
    name: "{{ web_packages }}"
    state: present
- name: 웹 서비스 기동
  ansible.builtin.systemd:
    name: httpd
    state: started
    enabled: true

- name: 가상 호스트 설정
  ansible.builtin.template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: '0644'
    # validate: /usr/sbin/httpd -t -f %s
  notify: restart httpd

- name: 3) 웹 소스 코드 생성
  ansible.builtin.copy:
    src: files/html/
    dest: "/var/www/vhosts/{{ ansible_hostname }}"
    owner: root
    group: root
