---
- name: Restore playbook
  hosts: webserver
  tasks:
    - name: Down the service with firewall
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled
    - name: Stop the service
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
      loop:
        - httpd
        - firewalld
    - name: Remove the package
      ansible.builtin.yum:
        name: "{{ ansible_local.custom.general.package }}"
        state: absent
