---
- name: 시간 동기화
  hosts: datacenters
  tasks:
    - name: NTP 서버에 시간 동기화
      # kr.pool.ntp.org
      ansible.builtin.import_role:
        name: rhel-system-roles.timesync

    - name: 타임 존 설정
      # Asia/Seoul -> 변수(host_timezone)
      ansible.builtin.timezone:
        name: "{{ host_timezone }}"
      notify: restart chronyd

  handlers:
    - name: restart chronyd
      ansible.builtin.systemd:
        name: chronyd
        state: restarted
