---
- name: 시간 동기화
  hosts: all
  tasks:

    - name: 타임 존 설정
      # Asia/Seoul -> 변수(host_timezone)
      ansible.builtin.timezone:
        name: Asia/Seoul

    - name: NTP 서버에 시간 동기화
      # kr.pool.ntp.org
      ansible.builtin.import_role:
        name: rhel-system-roles.timesync
      vars:
        timesync_ntp_servers:
          - hostname: kr.pool.ntp.org
            iburst: true
