---
- name: Restore factcheck.yml
  hosts: all
  gather_facts: false
  tasks:
    - name: Remove service on firewall
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: disabled
    - name: Service stop
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
      loop:
        - httpd
        - firewalld
    - name: Remove index.html
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    - name: Remove package
      ansible.builtin.yum:
        name: httpd
        state: absent
