---
- name: Restore playbook
  hosts: databases
  gather_facts: false
  vars:
    web_package: httpd     # 잘못된 정보 그대로 입력
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    - name: Stopped "{{ db_service }}" service
      ansible.builtin.service:
        name: "{{ db_service }}"
        state: stopped
      ignore_errors: yes

    - name: Remove "{{ db_package }}", "{{ web_package }}" packages
      ansible.builtin.yum:
        name:
          - "{{ db_package }}"
          - "{{ web_package }}"
        state: absent
