---
- name: MariaDB server is installed
  hosts: databases
  remote_user: root
  vars:
    db_packages:
      - mariadb-server
      - python3-PyMySQL
    db_service: mariadb
    resources_url: http://ansible.example.com
    config_file_url: "{{ resources_url }}/my.cnf.standard"
    config_file_dst: /etc/my.cnf
  tasks:
    - name: 1) packages are installed"
      ansible.builtin.yum:
        name: "{{ db_packages }}"
        state: present
      notify:
        - set db password

    - name: 2) Make sure the database service is running
      ansible.builtin.service:
        name: "{{ db_service }}"
        state: started
        enabled: true

    - name: 3) The file has been installed
      ansible.builtin.get_url:
        url: "{{ config_file_url }}"
        dest: "{{ config_file_dst }}"
        owner: mysql
        group: mysql
        force: yes
      notify:
        - restart db service

  handlers:
    - name: restart db service
      ansible.builtin.service:
        name: "{{ db_service }}"
        state: restarted

    - name: set db password
      community.mysql.mysql_user:
        name: root
        password: soldesk1.
        priv: '*.*:ALL'
        state: present
