---
- name: Restore
  hosts: databases
  remote_user: root
  vars:
    db_packages:
      - mariadb-server
      - python3-PyMySQL
    db_service: mariadb
    resources_url: http://ansible.example.com
    config_file_url: "{{ resources_url }}/my.cnf.standard"
    config_file_dst: /etc/my.cnf
  tasks:
    - name: 3) The file has been installed
      ansible.builtin.file:
        path: "{{ config_file_dst }}"
        state: absent
    - name: 2) Make sure the database service is running
      ansible.builtin.service:
        name: "{{ db_service }}"
        state: stopped
    - name: 1) packages are installed"
      ansible.builtin.yum:
        name: "{{ db_packages }}"
        state: absent
