---
- name: 0) 모듈 테스트
  hosts: all
  tasks:
    - name: 1) 로그 파일 수집
      ansible.builtin.fetch:
        src: /var/log/secure
        dest: "secure-backups/{{ inventory_hostname }}-securelog"
        flat: true
