---
- name: Restore createusers.yml
  hosts: devservers
  remote_user: devops
  become: true
  vars_files:
    - vars/secret.yml
  tasks:
    - name: 1) 유저 삭제하기
      ansible.builtin.user:
        name:
          - demouser2
          - demouser1
        state: absent
        remove: yes
