---
- name: 0) 다시 복원
  hosts: web1.example.com
  tasks:
  - name: 1) 방화벽 내리기
    ansible.posix.firewalld:
     service: http
     permanent: true
     immediate: true
     state: disabled
  - name: 2) httpd 시스템 내리기
    ansible.builtin.systemd:
      name: httpd
      enabled: false
      state: stopped
  - name: 3) httpd 서비스 삭제
    ansible.builtin.yum:
      name: httpd
      state: absent
  - name: 4) index.html 파일 삭제
    ansible.builtin.file:
      path: /var/www/html/index.html
      state: absent
