---
- name: 0) 웹서버 구축 - 변수 테스트
  hosts: webserver
  vars:
    web_pkg: httpd
    firewall_pkg: firewalld
    web_service: httpd
    firewall_service: firewalld
    python_pkg: python3-PyMySQL
    open_service: http
  tasks:
    ######################################
    # 1) 패키지 설치 - {{ web_pkg }} {{ firewall_pkg }} {{ python_pkg }}
    # 2) 웹서버 설정 - /var/www/html/index.html
    # 3) 웹 서비스 기동
    # 4) 방화벽에 등록
    ######################################
    - name: 1) 패키지 설치
      ansible.builtin.dnf:
        name:
          - "{{ web_pkg }}"
          - "{{ firewall_pkg }}"
          - "{{ python_pkg }}"
        state: present

    - name: 2) 웹 서버 설정 - /var/www/html/index.html
      ansible.builtin.copy:
        content: "My Web Server Test Page\n"
        dest: /var/www/html/index.html
        mode: '0644'

    - name: 3) 웹 서비스 기동
      ansible.builtin.systemd:
        name: "{{ web_service }}"
        enabled: true
        state: started

    - name: 3) 웹 서비스 기동
      ansible.builtin.systemd:
        name: "{{ firewall_service }}"
        enabled: true
        state: started
    - name: 4) 방화벽 등록
      ansible.posix.firewalld:
        service: "{{ open_service }}"
        permanent: true
        immediate: true
        state: enabled

- name: 1) 웹 확인
  hosts: localhost
  become: false
  tasks:
    - name: A) 웹 연결 확인
      ansible.builtin.uri:
        url: http://192.168.10.11
        status_code: 200
      register: web_results

    - name: B) 웹 요청 확인         # - debug: var=web+
      ansible.builtin.debug:
        var: web_results.msg
