---
- name: Restore Playbook.yml
  hosts: all
  vars_files:
    - vars/vars.yml
  tasks:
    ###############################
    # 1) 방화벽 포트 제거
    # 2) 서비스 종료
    # 3) 서비스 설정 삭제
    # 4) 패키지 삭제
    ###############################
    - name: 1) 방화벽 포트 제거
      ansible.posix.firewalld:
        service: "{{ open_service }}"
        permanent: true
        immediate: true
        state: disabled

    - name: 2) 서비스 종료
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: false
        state: stopped
      loop:
        - "{{ web_service }}"
        - "{{ firewall_service }}"

    - name: 3) 서비스 설정 삭제
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    - name: 4) 패키지 삭제
      ansible.builtin.dnf:
        name:
          - "{{ web_pkg }}"
          - "{{ python_pkg }}"
        state: absent

